[workspace]
members = ["crates/orinfer-engine", "crates/orinfer-cli", "crates/orinfer-api"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.88"
publish = false
license = "LGPL-3.0-or-later"

[workspace.dependencies]
orinfer-engine = { path = "crates/orinfer-engine" }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
