[package]
name = "orinfer-models"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
orinfer-model-sdk.workspace = true
serde.workspace = true
serde_json.workspace = true
half.workspace = true
sha2.workspace = true
hex.workspace = true
memmap2 = "=0.9.11"
safetensors = "=0.8.0"
