[package]
name = "orinfer-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
axum = "=0.8.9"
futures-util = "=0.3.34"
libc = "=0.2.190"
minijinja = { version = "=2.24.0", features = ["json"] }
orinfer-engine.workspace = true
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.151"
tokenizers = { version = "=0.23.2", default-features = false, features = ["fancy-regex"] }
tokio = { version = "=1.53.2", features = ["rt-multi-thread", "macros", "net", "sync", "signal", "time"] }

base64 = "=0.23.1"
image = { version = "=0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
reqwest = { version = "=0.13.5", default-features = false, features = ["blocking", "rustls"] }

[lints]
workspace = true
