"""Offline publication of the registered Rust Flash Next execution package.

Uses the validated TileLang reference to bind actual host ABI and storage aliases;
execution order is generated by the Rust implementation, never model data.
"""
import argparse
import ast
import hashlib
import json
from pathlib import Path
import shutil

import numpy as np
import torch
from safetensors import safe_open
from tools.model.flash_next.checkpoint import Checkpoint
from tools.model.flash_next.native import Model
from tools.model.flash_next.weights import FRONTEND
from tools.model.publication import file_hash, write_json, link_or_copy
from tools.operators.common import configure
from tools.operators.abi import parse_host, evaluate
from kernels.model.control import advance
from kernels.model.flash_control import selection

DTYPES={'float16':('f16','F16'),'bfloat16':('bf16','BF16'),'float32':('f32','F32'),
        'int8':('i8','I8'),'uint8':('u8','U8'),'uint16':('u16','U16'),
        'int32':('i32','I32'),'uint32':('u32','U32'),'int64':('i64','I64')}

class Publisher:
    def __init__(self, model, directory, *, reuse_data=False):
        self.model,self.root=model,directory
        self.reuse_data=reuse_data
        self.cache=directory/'cache';self.weights=self.cache/'weights';self.cpu=self.cache/'cpu'
        for p in (self.weights,self.cpu,self.cache/'kernels'):p.mkdir(parents=True,exist_ok=True)
        self.buffers={};self.scopes={};self.storage={};self.weight_map={};self.kernels=[];self.groups={};self.programs={};self.exports={}
        self.state=set();self.kv={};self.divisors={};self.number=0
    def buffer(self,tensor,name=None,scope='workspace'):
        pointer=tensor.untyped_storage().data_ptr();offset=tensor.data_ptr()-pointer
        if pointer not in self.storage:
            name=name or f'Scratch{self.number}';self.number+=1
            dtype=DTYPES[str(tensor.dtype).removeprefix('torch.')][0]
            size=tensor.untyped_storage().nbytes()
            b=dict(name=name,dtype=dtype,shape=[size//tensor.element_size()],layout='native_contiguous',alignment=256,access='read' if scope=='weights' else 'read_write')
            if name in self.buffers:
                old=self.buffers[name]
                if old['dtype']!=dtype or np.prod(old['shape'])!=np.prod(b['shape']):raise ValueError('Aliased controls have incompatible storage')
                if scope=='weights':
                    raw=tensor.contiguous().view(torch.uint8).flatten().cpu().numpy().tobytes()
                    if old['data']['sha256']!=hashlib.sha256(raw).hexdigest():raise ValueError('Shared immutable operands differ')
            else:
                self.buffers[name]=b;self.scopes[name]=scope
                if scope=='weights':
                    raw=tensor.contiguous().view(torch.uint8).flatten().cpu().numpy().tobytes()
                    if len(raw)!=size:raise ValueError('Immutable weights must span their storage')
                    b['shape']=list(tensor.shape)
                    b['data']=dict(tensor=name,sha256=hashlib.sha256(raw).hexdigest())
                    _,dtype=DTYPES[str(tensor.dtype).removeprefix('torch.')]
                    header=json.dumps({'__metadata__':{f'orin.layout.{name}':b['layout']},name:dict(dtype=dtype,shape=b['shape'],data_offsets=[0,len(raw)])},separators=(',',':')).encode()
                    header+=b' '*((-len(header))%8)
                    filename=f'weight-{len(self.weight_map):05d}.safetensors'
                    destination=self.weights/filename
                    if self.reuse_data and destination.is_file():
                        identity=hashlib.sha256();identity.update(len(header).to_bytes(8,'little'));identity.update(header);identity.update(raw)
                        if file_hash(destination)!=identity.hexdigest():raise ValueError('Reused prepared weight differs from source')
                    else:
                        with destination.open('xb') as stream:
                            stream.write(len(header).to_bytes(8,'little'));stream.write(header);stream.write(raw)
                    self.weight_map[name]=filename
            self.storage[pointer]=name
        return self.storage[pointer],offset
    def fixed(self,name,dtype,shape,scope='sequence'):
        self.buffers[name]=dict(name=name,dtype=dtype,shape=shape,layout='native_contiguous',alignment=256,access='read_write');self.scopes[name]=scope
    def bind(self,program,section,label,args,m):
        if label in ('gdn-history-copy','gdn-update-save'):
            left,lo=self.buffer(args[0]);right,ro=self.buffer(args[1]);assert lo==ro==0
            return dict(kind='copy',source=left,destination=right,bytes=args[0].numel()*args[0].element_size())
        key=label.split(':')[-1]
        if key not in self.exports:
            path=self.model.output/'aot'/key
            host=(path/'host.txt').read_text();launch,=parse_host(host)
            node=next(n for n in ast.parse(host).body if isinstance(n,ast.FunctionDef) and n.name=='call')
            api=[a.arg for a in node.args.args if a.arg not in ('kernels','stream')]
            assets={}
            for field,file in [('module','kernel.cubin'),('source','kernel.cu'),('host_abi','host.txt')]:
                dest=self.cache/'kernels'/key/file;dest.parent.mkdir(exist_ok=True)
                if not dest.exists():link_or_copy(path/file,dest)
                assets[field]=dict(file=str(dest.relative_to(self.cache)),sha256=file_hash(dest))
            self.exports[key]=(api,launch,assets)
        api,launch,assets=self.exports[key]
        scalars={'rows':args[0].shape[0],'m':m}
        tensors={name:value for name,value in zip(api,args)}
        values=[]
        for argument in launch['ordered_arguments']:
            expr,ctype=argument['value'],argument['ctype']
            if ctype=='ctypes.c_void_p':
                tensor=tensors[expr.removesuffix('.data_ptr()')]
                # PLE convolution's FP16 cast is a selected immutable operand.
                name,offset=self.buffer(tensor,f'PleConvHalf' if key.startswith('ple-conv-') and tensor is args[-2] else None,
                                        'weights' if key.startswith('ple-conv-') and tensor is args[-2] else 'workspace')
                values.append(dict(kind='buffer_slice',name=name,offset=offset) if offset else dict(kind='buffer',name=name))
            else:
                values.append(dict(kind={'ctypes.c_int32':'i32','ctypes.c_int64':'i64','ctypes.c_float':'f32','ctypes.c_uint32':'u32'}[ctype],value=evaluate(expr,scalars)))
        groups=self.groups.setdefault(program,{});ops=groups.setdefault(section,[])
        slot=sum(op['kind']=='kernel' for op in ops)
        name=f'{program}/{section}/k{slot}'
        dimensions=launch['launch_expressions']
        self.kernels.append(dict(name=name,**assets,symbol=launch['symbol'],
            grid=[evaluate(dimensions['gridDim'+s],scalars) for s in 'XYZ'],block=[evaluate(dimensions['blockDim'+s],scalars) for s in 'XYZ'],
            shared_memory_bytes=evaluate(dimensions['sharedMemBytes'],scalars),cooperative=False,args=values))
        return dict(kind='kernel',name=name)
    def plan(self,m):
        print('EXPORT PROFILE',m,flush=True)
        # Compile a full-capacity index scan; all live bounds remain device values.
        self.model.position=self.model.capacity-m
        plan=self.model.plan(m);self.model.position=0
        for key,name in [('embedding',f'M{m}_Embedding'),('ple_embedding',f'M{m}_Ple'),('output','Logits'),('token','Selected')]:
            self.buffer(plan[key],name,'sequence' if key in ('output','token') else 'workspace')
        for (_,args),label in zip(plan['ops'],plan['labels']):
            if label in ('gdn-history-copy','gdn-update-save'):self.buffer(args[0],f'M{m}_HistoryOut')
        body='decode' if m==1 else f'prefill_m{m}';head=f'head_m{m}'
        section='begin';ops=[]
        for index,((kernel,args),label) in enumerate(zip(plan['ops'],plan['labels'])):
            if index==plan['body_count']:break
            layers=[]
            for a in args:
                if isinstance(a,torch.Tensor):
                    name=self.storage.get(a.untyped_storage().data_ptr(),'')
                    if name.startswith('W_blk.') and not name.endswith('_table'):
                        layers.append(int(name.split('.')[1]))
            if layers:section=f'layer{min(layers)}'
            op=self.bind(body,section,label,args,m)
            self.groups.setdefault(body,{}).setdefault(section,[]).append(op);ops.append(op)
        advance_kernel=self.model.kernel(f'advance-{m}',lambda:advance(m))
        op=self.bind(body,'end',f'advance-{m}',(self.model.position_gpu,),m)
        self.groups[body].setdefault('end',[]).append(op);ops.append(op)
        head_ops=[]
        for (kernel,args),label in list(zip(plan['ops'][plan['body_count']:],plan['labels'][plan['body_count']:]))+[(op,f'greedy-partials-1-{self.model.V}' if i==0 else f'greedy-merge-1-{self.model.V}') for i,op in enumerate(plan['greedy_ops'])]:
            op=self.bind(head,'body',label,args,m);self.groups.setdefault(head,{}).setdefault('body',[]).append(op);head_ops.append(op)
        self.model.kernel('selection',selection)
        op=self.bind(head,'body','selection',(plan['token'],plan['token'][:1],plan['token'][1:]),m)
        # The controls use independent runtime-owned allocations, not pair slices.
        controls={'Pair':'Selected','Token':'Token','Status':'Status'}
        self.kernels[-1]['args']=[dict(kind='buffer',name=controls[a['value'].removesuffix('.data_ptr()')])
                                  for a in self.exports['selection'][1]['ordered_arguments']]
        self.groups[head]['body'].append(op);head_ops.append(op)
        self.programs[head]=head_ops
        self.programs[body]=ops+head_ops if m==1 else ops
        return plan
    def cpu_assets(self,source):
        assets=dict(version=1,vocab=self.model.V,eos=self.model.ple.eos,multipliers=self.model.ple.multipliers,
                    sizes=self.model.ple.sizes,offsets=self.model.ple.offsets,books=[],embedding=[],ple=[])
        books={};seen=set();golden=[]
        for label,names in [('embedding',['model.language_model.embed_tokens.weight']),('ple',self.model.ple.names)]:
            first=0
            for name in names:
                for p in source.parts[name]:
                    if p['kind'] not in ('e8p-embedding','int8-row'):raise ValueError('Unsupported CPU lookup representation')
                    dest=self.cpu/p['path'].name
                    if dest.name not in seen:
                        if not dest.exists():link_or_copy(p['path'],dest)
                        seen.add(dest.name)
                    if p['kind']=='int8-row':
                        weight=p['header'][p['keys']['weight']];scale=p['header'][p['keys']['scale']]
                        assets[label].append(dict(file=str(dest.relative_to(self.root)),sha256=file_hash(dest),offset=p['begin']+weight['data_offsets'][0],
                            scale_offset=p['begin']+scale['data_offsets'][0],first=first,rows=p['count']))
                        first+=p['count'];continue
                    with safe_open(p['path'],framework='np') as f:
                        table=f.get_tensor(p['keys']['table']);signs=f.get_tensor(p['keys']['signs'])
                    key=table.tobytes()+signs.tobytes()
                    if key not in books:
                        books[key]=len(books);assets['books'].append(dict(table=table.flatten().astype(int).tolist(),signs=signs.astype(int).tolist()))
                    info=p['header'][p['keys']['rows']]
                    assets[label].append(dict(file=str(dest.relative_to(self.root)),sha256=file_hash(dest),
                         offset=p['begin']+info['data_offsets'][0],first=first,rows=p['count'],book=books[key]))
                    first+=p['count']
        write_json(self.cpu/'inputs.json',assets)
        tokens=[42,248044,998,17,12345]
        history=[33,67]
        embedding=np.stack([self.model.embedding.read('model.language_model.embed_tokens.weight',t) for t in tokens])
        ple,_=self.model.ple.prepare(tokens,history)
        write_json(self.model.output/'input-golden.json',dict(tokens=tokens,history=history,embedding=embedding.view(np.uint16).flatten().astype(int).tolist(),ple=ple.view(np.uint16).flatten().astype(int).tolist()))
        return dict(file='cache/cpu/inputs.json',sha256=file_hash(self.cpu/'inputs.json'))
    def finish(self,source):
        inputs=self.cpu_assets(source)
        weight_bytes=sum(np.prod(b['shape'],dtype=np.int64).item()*{'u8':1,'i8':1,'u16':2,'f16':2,'bf16':2,'f32':4,'u32':4,'i32':4}[b['dtype']] for b in self.buffers.values() if b['access']=='read')
        write_json(self.weights/'model.safetensors.index.json',dict(metadata=dict(total_size=weight_bytes),weight_map=self.weight_map))
        metadata=dict(schema_version=2,target='sm_87',model='Qwen3.8-Flash-Next',chunk_tokens=512,max_context=self.model.capacity,
            vocab=self.model.V,toolchain={'tilelang':'0.1.15','torch':torch.__version__},buffers=list(self.buffers.values()),reset_buffers=sorted(self.state|{'Position','Token','Status'}),
            input='Input',token='Token',status='Status',logits='Logits',position='Position',weight_bytes=weight_bytes,
            weight_parameters=sum(np.prod(source.shape(n),dtype=np.int64).item() for n in source.parts if '.ple_embedding.' not in n),weight_scope='Flash Next GPU text weights including packed experts/scales/books',input_assets=inputs,
            kv_cache=dict(direct_prefill=True,demand_mapping=True,buffers=self.kv,prefix_divisors=self.divisors,prefill_workspace={},growth={}))
        write_json(self.cache/'build.json',dict(metadata=metadata,kernels=self.kernels,groups=self.groups,programs=self.programs,scopes=self.scopes,
            profiles=[{'tokens':m,'kind':'flash_recurrent'} for m in (16,128,512)]))
        return metadata

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--checkpoint',type=Path,required=True);p.add_argument('--model-output',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--context',type=int,default=262144);p.add_argument('--reuse-data',action='store_true',help='Verify and reuse immutable weights from an interrupted build')
    a=p.parse_args();configure();a.model_output.mkdir(parents=True,exist_ok=True)
    source=Checkpoint(a.checkpoint,verify_hashes=False)
    for name in ('config.json',*FRONTEND):
        if (a.checkpoint/name).is_file():shutil.copyfile(a.checkpoint/name,a.model_output/name)
    model=Model(source,a.context,a.output,use_graph=False);publish=Publisher(model,a.model_output,reuse_data=a.reuse_data)
    for logical,value in model.weights.items():
        if isinstance(value,dict):items=value.items()
        elif isinstance(value,tuple):items=zip(('weight','scale'),value)
        else:items=[('value',value)]
        for suffix,tensor in items:publish.buffer(tensor,f'W_{logical}_{suffix}','weights')
    for logical,tensor in model.states.items():
        name='State_'+logical.replace(':','_');publish.buffer(tensor,name,'sequence');publish.state.add(name)
        if logical in model.prefix_divisors:
            publish.kv[name]=tensor.untyped_storage().nbytes()//a.context
            if model.prefix_divisors[logical]!=1:publish.divisors[name]=model.prefix_divisors[logical]
    publish.buffer(model.position_gpu,'Position','sequence');publish.buffer(model.lengths,'Length','sequence')
    publish.buffer(model.position_out,'PositionOut','workspace')
    for name,dtype,shape in [('Input','i32',[512]),('Token','i32',[1]),('Status','i32',[1]),('LastIndex','i32',[1])]:publish.fixed(name,dtype,shape)
    for m in (512,128,16,1):
        publish.plan(m)
        write_json(publish.cache/'bindings.json',dict(buffers=publish.buffers,scopes=publish.scopes,kernels=publish.kernels,groups=publish.groups,programs=publish.programs))
    publish.finish(source)
    from tools.model.flash_next.checks.deployment import freeze
    freeze(model,a.checkpoint,a.output)
    print('FLASH BUILD COMPLETE',flush=True)
if __name__=='__main__':main()
